### ISSUE TITLE
Hi Joel! I'm Kieran the CTO of gifs.com

### ISSUE THREAD

**Issue by kieranoreilly** [jglovier/ama#1]
Hi Joel! Saw your awesome library of gifs and definitely love your ama fork. Would you be up for a google hangout one day? I'd love to tell you about what we are doing, the opportunities moving forward and ask about your work.
Best,
Kieran

**Comment by jglovier** [comment]
Ohai @kieranoreilly! Congrats on being my first question! :smile: 

Why don't you shoot me an email at _[my email address]_ and we can chat a bit more about what you're after there. Thx.
