### ISSUE TITLE
yo yo

### ISSUE THREAD

**Issue by hoolio** [jglovier/ama#12]
it’s @hoolio! 

Check your DMs, please — talk soon 

🙏🏽🙏🏼🙏🏽

**Comment by jglovier** [comment]
@hoolio!! Hi there 👋 

I've checked all of my DMs, but I don't see anything from you anywhere. 😄 What platform??

**Comment by jglovier** [comment]
Oh - just kidding! I found it hiding in the message requests. Will respond soon. 😊 :v:

**Comment by jeffrafter** [comment]
👀

**Comment by zeke** [comment]
👀
