### ISSUE TITLE
Request to use your "Pull Requests Welcome" image with credit included

### ISSUE THREAD

**Issue by jmeridth** [jglovier/ama#13]
@jglovier May I use your [Pull Requests Welcome](https://dribbble.com/shots/3775558--Pull-Requests-Welcome-hand-painted-sign) image in my GitHub personal README on my profile.  It is [this](https://github.com/jmeridth/jmeridth/blob/main/README.md) that renders [here](https://github.com/jmeridth).  I can either (or both) make the image clickable to go to that dribble URL or another URL of your choosing and/or put text under the image with your name so it is very visible.

If not, no worries. I don't want to use your image without your permission.

NB: Awesome image

Cheers.

**Comment by jglovier** [comment]
Hi @jmeridth! Thanks for asking, and of course you can! I appreciate the credit link - feel free to just link the image itself to the dribbble URL, text link not necessary.

❤️

**Comment by jglovier** [comment]
PS - thanks for your patience with my long delayed response here. 😸

**Comment by jmeridth** [comment]
@jglovier Thank you very much.  Cheers.

**Comment by jmeridth** [comment]
@jglovier Want to double check here.  May I use this image in a public presentation I'm giving soon.  I will give credit on the slide and in the speaker notes.  If I have open-ended permission as long as credit is given, that'd be 👍 .  Absolutely love this image.

If you decline, no worries.  Thank you for your time.

**Comment by ratchanonsuttawas** [comment]
Pull request wellcome

**Comment by jglovier** [comment]
@jmeridth sure, feel free to use it for your presentation, and thanks for asking. Apologies again for the delayed response - hope it's not too late for your talk.
