### ISSUE TITLE
Jekyll Resume print styles

### ISSUE THREAD

**Issue by lahtikarri** [jglovier/ama#2]
Where would you recommend putting the print styles? In the existing sass files or creating a separate file for the print styles and then calling it where needed?

**Comment by jglovier** [comment]
> In the existing sass files or creating a separate file for the print styles and then calling it where needed?

@lahtikarri good question! I'd say it's totally up to you and how you'd like to maintain your own fork. If for convenience you want to put it in the existing sass file, go for it! Or, if you'd like to keep those styles separate, that's cool too.

Also, if you'd like to open an issue in the jekyll resume repo to add print styles, that'd be helpful! I think I had intentions to do that but never got around to it, so having a tracking issue would be :cool:.
