### ISSUE TITLE
How to use the built_site_index?

### ISSUE THREAD

**Issue by frankmeeuwsen** [jglovier/ama#3]
Hi Joel

I love your gif-repo, I forked it for my own collection and also learn some github along the way. After forking and adding some of my own files in a new directory I could commit and push it. But my own site http://gifs.frankmeeuwsen.com doesn't show the new files (directory a-list)
I assume I have to rebuild the site as you say in the readme.md? But how does this work? Also, every now and again the subdomain gifs.frankmeeuwsen.com is not accessible. Any idea how this is possible?
Thanks and BTW love this AMA style!

Frank

**Comment by jglovier** [comment]
Hi @frankmeeuwsen! Glad you like the gifs repo!!

> I assume I have to rebuild the site as you say in the readme.md? But how does this work?

To rebuild the site, you need to go to the repository root in terminal and run `scripts/rebuild_site_index` which will generate a new index for the site. Then, commit and push the changes and everything should work as expected. :sparkles:

> Also, every now and again the subdomain gifs.frankmeeuwsen.com is not accessible. Any idea how this is possible?

Sorry, no idea why you'd experience that without more info on the problem. Is it a 500 error? Does it just keep loading and never load, or instead resolve to something else? My guess is that it's a DNS configuration issue, or it could even just be a momentary outage of GitHub Pages servers (it does happen from time to time, if we are upgrading things, etc).

**Comment by frankmeeuwsen** [comment]
_Update_: I updated Bundler and after that everything seemed to work without an error. I still need to figure out why my new directory is not included on the page.

# 

Well, that's exactly it. How do I run rebuild_site_index? Because I get a message "/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- builder (LoadError)
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from script/build_site_index:3:in `<main>'"
If I need to update something or check something else, if you can point me in the right direction I might find a solution myself. 
Anyway, thanks so far!

**Comment by jglovier** [comment]
> Update: I updated Bundler and after that everything seemed to work without an error.

Ahh, yeah that'll do it.

> I still need to figure out why my new directory is not included on the page.

Are you saying that after you run the script, your site isn't updated?

**Comment by frankmeeuwsen** [comment]
Didn't have enough patience after commit and push. It works now. Thanks!

**Comment by jglovier** [comment]
:metal:
