### ISSUE TITLE
404 gifs

### ISSUE THREAD

**Issue by johnzzon** [jglovier/ama#5]
Yo dude, your gifwit-library is awesome, but a lot of the gifs are missing :(
For example http://gifs.joelglovier.com/yes/head-b0b.gif

They make my gifwit get stuck at the particular gifs:
http://i.imgur.com/Bxu5ZO0.png

Is there a way to remedy this?

Sincerely,
Emil

**Comment by jglovier** [comment]
Hey @Johnzzon! Glad you like the project!

> but a lot of the gifs are missing...They make my gifwit get stuck at the particular gifs:

Unfortunately, I haven't used the gifwit library much, and the gifwit developer added support for it himself. So you could always open an issue on the gifs repo about that and cc him. But rebuilding from the index should remedy the problem.
