### ISSUE TITLE
Curiosity about a possible Summer Design Internship at Github

### ISSUE THREAD

**Issue by priyank1205** [jglovier/ama#6]
Hey Joel. Sorry for bothering you, but I was wondering if there could be the possibility of procuring a summer internship at GitHub for User Experience Design (or Product Design). I'd really love to learn from you !

**Comment by jglovier** [comment]
hey @priyank1204! We certainly do have an internship program, and you can apply for it at https://internships.github.com for 2017 openings.

**Comment by priyank1205** [comment]
Hi Joel! Thanks for replying. I could not see any UX Research/Design internship listed out there, and hence was wondering if there was a possibility of such an opening to be made. Thanks again for the prompt reply!

**Comment by jglovier** [comment]
@priyank1205 sorry, but the only opportunities I'm aware of are the ones listed at https://github.com/about/jobs#internships.
