### ISSUE TITLE
Fizzy for Visual Studio Code?

### ISSUE THREAD

**Issue by jaredreich** [jglovier/ama#7]
I am a huge fan of your Fizzy theme for Atom, but can't find anything that feels quite right in VSCode. Would be awesome if you published Fizzy in that extension store as well.

Thanks for reading!

**Comment by jglovier** [comment]
Great idea, @jaredreich! I don't have any experience using VSCode, or developing themes for it, but if there's some interest in using Fizzy in VSCode I'd be happy to look into porting it.

...or, you could always make a port! :wink:

Cheers!
Joel
