### ISSUE TITLE
HospitalRun

### ISSUE THREAD

**Issue by developerno1** [jglovier/ama#9]
hey im an independent developer and have been working on a HMS for the developing world myself.. try out http://www.ahmspro.com to checkout my work.. although it was quite old, but extensive. now just found out your project and am really intrested in contributing further.. will be waiting for your response to start!

**Comment by jglovier** [comment]
Hi @developerno1! Thanks for your interest in contributing to HospitalRun. Best place to start is on [this Contributors page](http://hospitalrun.io/contribute/), and follow the links. If you have questions, jump into the community Slack and ask away!

Very cool to see that you have been working on an HMS for a while. ✨ 🏥 ❤️
